CC = g++
CFLAGS = -Wall -g

all: lab2

lab2: main.o
		$(CC) $(CFLAGS) main.o -o lab_di_matrix

main.o: main.cpp array_sequence.hpp dynamic_array.hpp linked_list.hpp Sequence.hpp di_matrix_array.hpp di_matrix_list.hpp di_matrix_menu.hpp
		$(CC) -c main.cpp -o main.o
