CC = g++
CFLAGS = -Wall -g

all: lab2

lab2: main.o
		$(CC) $(CFLAGS) main.o -o lab2

main.o: main.cpp array_sequence.hpp dynamic_array.hpp linked_list.hpp menu.hpp Sequence.hpp vector.hpp vector_array.hpp vector_list.hpp
		$(CC) -c main.cpp -o main.o
